Reviews/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
	# Examples:


# url(r'^inicio/','Registro.views.index'),
	
    #url(r'^$','Registro.views.index',name="home"),    
    url(r'^$','Core.views.index',name='index'),
    url(r'^miembros/$','Core.views.home',name='home'),
    (r'^accounts/', include('allauth.urls')),
    #url(r'^registrar/','Registro.views.registro'),
    #url(r'^login/','Registro.views.login'),
    #url(r'^noActivo/','Registro.views.noActivo'),
    #url(r'^logout/','Registro.views.logout'),
    #url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^confirmar/(?P<confirmation_code>\w+)/(?P<user_name>.+)', ('Registro.views.confirm')),
    #url(r'^succes/','Registro.views.registroCorrecto'),    
    url(r'^nuevoEstablecimiento/','Contenido.views.Establecimiento_nuevo'),	

    ###URLS PARA PERFIL
    url(r'^perfil/(?P<id>\w+)/', ('Registro.views.verPerfil')),
    url(r'^procfile/', ('Registro.views.procfile')),
    url(r'^procfileCreate/', ('Registro.views.procfileCreate')),    
    url(r'^modificarPerfil/(?P<id>\d*)',('Registro.views.modificarPerfil')),
    url(r'^procfileSync/', ('Registro.views.procfileSync')),   
    url(r'^confperfil/(?P<pide>\w+)/(?P<usPerfil>.+)', ('Registro.views.confPerfil')),


    url(r'^Establecimientos2/','Contenido.views.Establecimientos2'),
    url(r'DetalleEstablecimiento/(?P<id>\d*)',('Contenido.views.DetalleEstablecimiento')),
    
    url(r'^NuevaReview/(?P<id>\d*)/','Contenido.views.NuevaReview',name='NuevaReview'),
    
    
    url(r'^modificarReview/(?P<id>\d*)',('Contenido.views.modificarReview')),
    url(r'^nuevoComentario/',('Contenido.views.nuevoComentario')),
    
    ###URLS PARA DENUNCIAS ###
    url(r'^denunciar/',('Contenido.views.denunciar')),
    url(r'^denuncias/',('Contenido.views.denuncias')),
    url(r'^moderar/(?P<tipo>\w+)/(?P<id>\d*)$',('Contenido.views.moderar')),
    url(r'eliminarContenido/(?P<id>\d*)$',('Contenido.views.eliminarContenido')),
    url(r'permitirContenido/(?P<id>\d*)$',('Contenido.views.permitirContenido')),
    #url(r'bloquearContenido/',('Contenido.views.bloquarContenido')),


    ###URL PARA ACTUALIZAR CON AJAX LAS NOTIFICACIONES A LOS USUARIOS ###
    url(r'buscarNotificacion/',('Contenido.views.buscarNotificacion')),
    
    ###URLS PARA EL FILTRADO DE CONTENIDOS ####
    url(r'filtrar/',('Contenido.views.filtrar')),
    url(r'filtrarDenuncias/',('Contenido.views.filtrarDenuncias')),

    
    url(r'^Refresh/','Contenido.views.Refresh'),
    url(r'^search/', include('haystack.urls')),    
    url(r'^searchEstablecimiento/', 'Contenido.views.searchEstablecimiento'),    
    
    ### URL Para generar robots.txt
    url(r'^robots\.txt$', include('robots.urls')),


    ###URL Para compartir Redes Sociales
    url(r'postTweet/',('Contenido.views.postTweet')),
    url(r'messageTwitter/',('Contenido.views.sendMessageTwitter')),
    url(r'followers/',('Contenido.views.searchFollowers')),
    url(r'faceWall/',('Contenido.views.wallPost')),
    url(r'faceFriends/',('Contenido.views.faceFriends')),
    url(r'faceMessage/',('Contenido.views.faceMessage')),
    )
    

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
		url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.STATIC_ROOT,
		}),
)

Contenido/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Establecimiento(models.Model):
	nombre = models.CharField(max_length = 50)
	ciudad = models.ForeignKey('Ciudad')
	puntaje = models.IntegerField()
	tipo = models.ForeignKey('TipoEstablecimiento',default=1)
	descripcion = models.TextField(max_length= 1000)
	foto = models.ImageField(upload_to ='Establecimiento')
	estado=models.CharField(max_length =15,default="Activo")
	creviews=models.IntegerField(default=0)
	direccion = models.CharField(max_length =100,null=True,blank=True,default="No asignada")
	
	def __str__(self):
		return self.nombre
	#Comentado porque me da error a la hora de cargar una nueva review	
	#def save(self):
	#	image = Image.open(self.foto)
	#	size=(350,200)
	#	image = image.resize(size, Image.ANTIALIAS)
	#	image.save(self.photo.path)

	def calcular_puntaje(self):
		promedio = self.contenido_set.all().aggregate(Avg('puntaje'))['puntaje__avg']
		if promedio == None:
			return promedio
		else:
			return int(promedio)


PUNTAJES= (
(1, ("1")),
(2, ("2")),
(3, ("3")),
(4, ("4")),
(5, ("5")),
)	
	
class Contenido(models.Model):
	autor = models.ForeignKey(User)
	titulo = models.CharField(max_length= 50, null=False, blank=False)
	texto = models.TextField(max_length = 500, null=False, blank=False)
	fecha = models.DateTimeField()
	tipo = models.CharField(max_length=50)
	estado = models.CharField(max_length =15,default="Activo")
	puntaje = models.IntegerField(choices=PUNTAJES)
	Establecimiento = models.ForeignKey('Establecimiento',blank=True,null=True)
	relacionado = models.ForeignKey('Contenido',blank = True,null=True)
	def __unicode__(self):
		return 	self.autor.username + self.tipo
	def __str__(self):
		return 	self.autor.username + self.tipo

class ContenidoAntiguo(models.Model):
	autor = models.ForeignKey(User)
	titulo = models.CharField(max_length= 50,default="Contenido")
	texto = models.TextField(max_length = 500)
	fecha = models.DateTimeField()
	tipo = models.CharField(max_length=50)
	estado = models.CharField(max_length =15,default="Activo")
	puntaje = models.IntegerField(choices=PUNTAJES)
	Establecimiento = models.ForeignKey('Establecimiento',blank=True,null=True)
	relacionado = models.ForeignKey('Contenido',blank = True,null=True)
	
	def __str__(self):
		return 	self.autor.username + "contenido " + self.titulo

class TipoEstablecimiento(models.Model):
	tipo = models.CharField(max_length = 50)
	def __str__(self):
		return self.tipo

class Provincias(models.Model):
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return self.nombre

class Ciudad(models.Model):
	nombre= models.CharField(max_length=100)
	provincia_id= models.ForeignKey('Provincias')
	def __str__(self):
		return self.nombre


class Ubicacion(models.Model):
	#fields
	ciudad = models.CharField(max_length=100)
	provincia = models.CharField(max_length=50)
	pais = models.CharField(max_length=50)
	latitud = models.CharField(max_length=15)
	longitud = models.CharField(max_length=15)

class Denuncias(models.Model):
	autor = models.ForeignKey(User)
	tipo = models.CharField(max_length=25)
	fecha = models.DateTimeField()
	id_denunciado= models.IntegerField()
	razon = models.CharField(max_length=100)
	categoria= models.ForeignKey('CategoriaDenuncias',blank=True,null=True)
	estado = models.CharField(max_length=25,default="Activo")
	def __str__(self):
		return self.autor.username 

class CategoriaDenuncias(models.Model):
	nombre= models.CharField(max_length=25)
	def __str__(self):
		return self.nombre

Contenido/views.py
# -*- encoding: utf-8 -*-

from django.shortcuts import render
from forms import *
from django.template import RequestContext
from django.shortcuts import render, render_to_response,redirect,get_object_or_404
from models import *
from Mensajes.models import *
from Registro.models import * 
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from datetime import datetime
from django.http import HttpResponseRedirect, HttpResponse
#Para el paginador
import funciones
import tweet
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from operator import itemgetter, attrgetter, methodcaller

from haystack.query import SearchQuerySet
from haystack.views import SearchView

from allauth.socialaccount.models import SocialAccount,SocialToken,SocialApp
import facebook
import tweepy

def buscar(id):
	establ=get_object_or_404(Establecimiento,pk= id)
	return establ


@login_required(login_url="/accounts/login/")
def Establecimiento_nuevo(request):
	if request.method=="POST":
		form=FormEstablecimiento2(request.POST,request.FILES)
		
		nombre = request.POST["nombre"]
		ti = request.POST["tipo"]
		tipo = get_object_or_404(TipoEstablecimiento,pk=ti)
		codpos = request.POST["ciudad"]
		lista = codpos.split(",")
		ciudSeleccionada=lista[0]		
		provSeleccionada=lista[1]
		if not Provincias.objects.filter(nombre = provSeleccionada):
			provincia = Provincias()
			provincia.nombre=provSeleccionada
			provincia.save()
		else: 
			provincia = Provincias.objects.get(nombre= provSeleccionada)

		if not Ciudad.objects.filter(nombre = ciudSeleccionada,provincia_id=provincia):#provincia_id.nombre= provSeleccionada):
			ciudad= Ciudad()
			ciudad.nombre=ciudSeleccionada
			
			ciudad.provincia_id=provincia
			ciudad.save()
		else:
			ciudad = Ciudad.objects.get(nombre=ciudSeleccionada,provincia_id= provincia)
		puntaje = 1 
		descripcion = request.POST["descripcion"]
		foto = request.FILES["foto"]
		E = Establecimiento(nombre=nombre,ciudad = ciudad,puntaje = puntaje,tipo = tipo,descripcion = descripcion,foto = foto)
		E.save()
		return redirect('/Establecimientos2/')
	else:
		form= FormEstablecimiento2()
		return render(request,'EstablecimientoNuevo.html',{'form':form})




def Establecimientos2(request):                            
	return render_to_response('Establecimientos2.html',context_instance=RequestContext(request))


#@login_required(login_url="index")
def DetalleEstablecimiento(request,id):
	establ = buscar(id)
	form= FormComentario()
	#comentarios = Contenido.objects.filter(tipo="Review",Establecimiento=establ,estado="Activo" )
	#return render_to_response('DetalleEstablecimiento.html',{'form':form,'Establecimiento':establ,'Reviews':comentarios},context_instance=RequestContext(request))
	fDenuncia= FormDenuncia()
	fReview= FormNewReview()
	lista=[]
	perfilUsr, perfil = None, None
	reviews= Contenido.objects.filter(tipo="Review",Establecimiento=establ ,estado="Activo")
	for r in reviews:
		#c = Contenido.objects.filter(tipo="Comentario",relacionado=r.id,estado="Activo")
		try:
			perfilUsr  = perfilUsuario.objects.get(usuario_id=r.autor.id)

		except perfilUsuario.DoesNotExist:
			perfilUsr = None

		if perfilUsr != None:
			try:
				perfil = Perfil.objects.get(pk=perfilUsr.id)

			except Perfil.DoesNotExist:
				perfil = None	

		if perfil != None:
			lista.append((r,perfil.foto))
		else:
			lista.append((r,'Perfiles/no-user.png'))

	return render_to_response('DetalleEstablecimiento.html',{"lista":lista,"Establecimiento":establ,"fReview":fReview,'form':form,"fDenuncia":fDenuncia},context_instance=RequestContext(request))




@login_required(login_url="/accounts/login/")
def NuevaReview(request,id):
	if request.method=="POST":
		autor= request.user
		texto = request.POST["texto"]
		fecha= datetime.now()
		titulo = request.POST["titulo"]
		tipo = "Review"
		activo= "Activo"
		puntaje = request.POST["puntaje"]
		establecimiento = buscar(id)
		try:
			R = Contenido(autor=autor,titulo = titulo,texto = texto,fecha= fecha,tipo=tipo,estado=activo,puntaje=puntaje,Establecimiento=establecimiento)
			R.save()
		except Exception, e:
			raise e
			print e
			establ = buscar(id)
			form = FormNewReview()
			return	render(request,'NuevaReview.html',{'form':form,'Establecimiento':establ})
		
		establ = buscar(id)

		prom = funciones.promedioReviews(establ)	
		establ.puntaje = prom
		establ.save()
		return redirect('Contenido.views.DetalleEstablecimiento', id=establ.id)
		#return DetalleEstablecimiento(request,establ.id)
		
		#return redirect("DetalleEstablecimiento/"+str(establ.id))
		#comentarios = Contenido.objects.filter(tipo="Review",Establecimiento=establ )
		#return render_to_response('DetalleEstablecimiento.html',{'Establecimiento':establ,'Reviews':comentarios},context_instance=RequestContext(request))
	


@login_required(login_url="/accounts/login/")
def modificarReview(request,id):
	if request.method =='POST':
		antigua =Contenido.objects.get(pk=id)
		RA =ContenidoAntiguo()
		#Generar la version de la Review
		RA.autor= request.user
		RA.titulo= antigua.titulo
		RA.texto=antigua.texto
		RA.fecha= datetime.now()
		RA.estado="Versionado"
		RA.tipo="Review"
		RA.puntaje = antigua.puntaje
		RA.Establecimiento =  antigua.Establecimiento
		#Generar la nueva Review
		autor= request.user
		texto = request.POST["texto"]
		fecha= datetime.now()
		titulo = request.POST["titulo"]
		tipo = "Review"
		puntaje = request.POST["puntaje"]
		establecimiento = antigua.Establecimiento
		try:
			#Salvamos nueva version
			R = Contenido(autor=autor,titulo = titulo,texto = texto,fecha= fecha,tipo=tipo,estado="Activo",puntaje=puntaje,Establecimiento=establecimiento)
			R.save()

			RA.relacionado=R
			#Salvamos la version antigua
			RA.save()
			antigua.delete()
		except Exception, e:
			raise e
			print e
			review = Contenido.objects.get(pk=id)
			form = FormNewReview(instance= review)
			return	render(request,'modificarReview.html',{'form':form,'Establecimiento':review.Establecimiento})
	
		establ = buscar(R.Establecimiento.id)
		##################  Modificar  Promedio ##########################
		prom = funciones.promedioReviews(establ)	
		establ.puntaje = prom
		establ.save()

		comentarios = Contenido.objects.filter(tipo="Review",Establecimiento=establ )
		return render_to_response('DetalleEstablecimiento.html',{'Establecimiento':establ,'Reviews':comentarios},context_instance=RequestContext(request))
	else:
		review = Contenido.objects.get(pk=id)
		form = FormNewReview(instance =review)
		return	render(request,'modificarReview.html',{'form':form,'review':review})


@login_required(login_url="/accounts/login/")
def eliminarContenido(request,id):
	denuncias = Denuncias.objects.filter(id_denunciado=id)
	bandera=0
	for denuncia in denuncias:
		denuncia.estado	="Eliminada"
		denuncia.save()
	contenido = Contenido.objects.get(pk=id)
	autor = contenido.autor
	if contenido.tipo =="Review":
		######Cambiar el puntaje del establecimiento######
		bandera=1
		establ = buscar(contenido.Establecimiento.id)
		prom = funciones.promedioReviews(establ)	
		establ.puntaje = prom
		establ.save()
		relacionados = Contenido.objects.filter(relacionado=contenido)
		for r in relacionados:
			r.estado="Eliminado"
			r.save()
		notificar = funciones.notificacion(request.user,autor,"ReviewDenunciadoEliminado") 
	else:
		notificar = funciones.notificacion(request.user,autor,"ComentarioDenunciadoEliminado") 
	contenido.estado="Eliminado"
	contenido.save()
	if bandera==1:
		#establ = buscar(establ.id)
		prom = funciones.promedioReviews(establ)	
		establ.puntaje = prom
		establ.save()

	direccion =str(request.META.get("HTTP_REFERER"))
	if "/moderar/" in direccion:
		
		lDenuncias = Denuncias.objects.all().order_by("fecha")
		return render_to_response('denuncias.html',{'denuncias': lDenuncias},context_instance=RequestContext(request))
	else:
		return redirect("/")


@login_required(login_url="/accounts/login/")
def nuevoComentario(request):
	if request.method =='POST':
		try:
		
			autor = request.user
			texto = request.POST['texto']
			titulo=" "
			tipo = 'Comentario'
			fecha = datetime.now()
			estado="Activo"
			puntaje = 0
			id_relacionado= request.POST["review_id"]
			relacionado= Contenido.objects.get(pk=id_relacionado)

			Cont = Contenido(autor = autor,texto=texto,titulo=titulo,relacionado= relacionado,tipo=tipo,fecha=fecha,estado=estado,puntaje=puntaje)
			Cont.save()
			establ = relacionado.Establecimiento
		
			lista=[]
			reviews= Contenido.objects.filter(tipo="Review",Establecimiento=establ ,estado="Activo")
			for r in reviews:
				c = Contenido.objects.filter(tipo="Comentario",relacionado=r.id, estado="Activo")
				lista.append((r,c))
			notificar = funciones.notificacion(autor,relacionado.autor,"Comentario")
			return render_to_response('DetalleEstablecimiento.html',{"lista":lista,"Establecimiento":establ},context_instance=RequestContext(request))

		#return render_to_response('DetalleEstablecimiento.html',{'Establecimiento':establ,'Reviews':reviews},context_instance=RequestContext(request))
		except Exception, e:
			raise e
	else:	
		pass



@login_required(login_url="/accounts/login/")
def denunciar(request):
	tipo = request.POST["tipo"]
	nu= request.POST["id_denuncia"]
	print "numero " + nu
	num = int(nu,10)
	estab=""
	if tipo == "Review":
		contenido = Contenido.objects.get(pk=num)
		tipo = "Review"	
		estab= contenido.Establecimiento.id	
	elif tipo == "Comentario":
		contenido = Contenido.objects.get(pk=num)
		tipo = "Comentario"
	elif tipo == "Usuario":
		contenido = User.objects.get(pk=num)
		tipo= "Usuario"
	else:
		pass
	autor = request.user
	cataux= request.POST["categoria"]
	categoria=CategoriaDenuncias.objects.get(id=cataux)
	fecha = datetime.now()
	id_denunciado = num
	razon = request.POST['razon']
	denuncia = Denuncias(autor= autor, fecha=fecha,id_denunciado=id_denunciado,razon=razon,tipo=tipo,categoria=categoria)
	denuncia.save()

Contenido/templates/DetalleEstablecimiento.html
{% extends "base.html" %}
{% load staticfiles %}

{%block head_title%} {{Establecimiento.nombre}}{%endblock%}

{%block extra_head%}
<style type="text/css">
    .parallax-container{
       height: 200px;
       background-color: rgba(0, 0, 0, 0.55);
   }

   .page-title{
    color:#fff;
    font-size: 50px;        
    font-weight: 500;        
    text-shadow: 0px 0px 10px #393939; 
    text-transform: uppercase;   
}

.first-card{    
    margin-top: 30px;
    padding-bottom: 30px;
}

.img-card{
    width:50%;
}

.img-card img{
    width: 100%
}

.ubicacion{
    margin-bottom: 15px;
}

body{
    background-color: #ededed;
}

.card:not(.first-card){
    padding:40px;
}
.form-comentario{    
    width: 100%;
}

.star-filled{
    color:#ffd700;
}

.star-empty{
    color: #e0e0e0;    
}

.rating-widget{
    margin-top: 40px;
}

.field-puntaje{
    padding: 55px 0 60px;
}

.foto{
    max-height: 500px;
    overflow: hidden;
}

.form-comentario h5, .comentarios h5{
    margin-bottom:40px;
}
.collection .collection-item.avatar{
    height: auto;
}

.comentarios .botones{
    padding: 20px 0;
    text-align: right;
}

.input-field label{
    left:0;
}
</style>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 'your-app-id',
      xfbml      : true,
      version    : 'v2.3'
  });
};

(function(d, s, id){
   var js, fjs = d.getElementsByTagName(s)[0];
   if (d.getElementById(id)) {return;}
   js = d.createElement(s); js.id = id;
   js.src = "//connect.facebook.net/en_US/sdk.js";
   fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %}

{% block body %}

<!--<div class="container">
    include "busquedaAvanzada.html"
</div>-->

<div class="container">
    <div class="card first-card center-align">
    <div class="foto">
        <img src="/media/{{Establecimiento.foto}}">
    </div>
        <div class="container"><h4 class="center-align">{{Establecimiento.nombre}}</h4>
        <p> {{Establecimiento.descripcion}}</p>        
        <div class="col s12 ubicacion"><i class="mdi-action-room"></i>&nbsp;{{Establecimiento.ciudad.nombre}} , dirección : {{Establecimiento.direccion}} </div>
        </div>    
        <div class="fb-share-button" data-href="http://nightadvisor.herokuapp.com/" data-layout="button_count"></div>

    </div>        
    
    <div class="card form-comentario">
        <div>
            <h5>Comentá tu experienia en {{Establecimiento.nombre}}</h5>
        </div> 
        <form id="f-comentario" action="/NuevaReview/{{Establecimiento.id}}/" method="POST">
            {% csrf_token%}
            {% if form.errors %}
            {% for field in fReview %}
            {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}                    
            <div class="input-field col s12">
                
                  {{fReview.titulo}}                  
                  <label for="titulo">Título</label>
                
            </div>  
            <div class="input-field col s12">
                
                  <textarea id="id_texto" name="{{fReview.texto.name}}" class="materialize-textarea"></textarea>                      
                  <label for="texto">Texto</label>
                
            </div>
            <div class="input-field col s12 field-puntaje">   
                <label for="puntaje">Puntaje</label>
                <input id="rating-widget" type="hidden" name="puntaje" class="rating" data-filled="fa fa-star fa-2x star-filled" data-empty="fa fa-star-o fa-2x star-empty"/>
            </div>                                         
            <button class="primaryAction btn waves-effect waves-light" type="submit">Comentar<i class="mdi-content-send right"></i></button>
            <input type="hidden" name="id" id='id' value="{{Establecimiento.id}}" />
            <input type="hidden" name="tipo" id='tipo' value="Review" />
        </form>         
    </div>
    
    <div class="comentarios card">
        {%if lista|length >= 1%}            
            <h5>Reviews de visitantes</h5>    
            <ul class="collection" id="image-test">    
            {%for R in lista%}                        
                <li class="collection-item avatar">
                    <img src="/media/{{R.1}}" alt="{{R.0.autor.username}}" class="circle tooltipped" data-position="bottom" data-delay="50" data-tooltip="{{R.0.autor.username}}"/>
                    <span class="title" id="{{R.id}}">{{R.0.titulo}}</span>
                  <p><input type="hidden" class="rating" readonly="True" data-filled="fa fa-star fa-1x star-filled" data-empty="fa fa-star-o fa-1x star-empty" value="{{R.0.puntaje}}"><br>
                     {{R.0.texto}}<br>
                    <div class="botones">
                        {%if user != R.0.autor%}<!-- Si no soy el autor de la review,la puedo denunciar-->                        
                        <a href="#myModalDenuncia" id="btnDenunciaReview" type="button" class="btn-floating btn btn-large waves-effect waves-light modal-trigger" data-id="{{R.0.id}}" id="btnDenuncia"><i class="fa fa-flag-o"></i></a>
                        {%endif%}

                        {%if user.is_staff%}<!-- Si el user es staff, puede bloquear contenido-->
                        <!--<a href="#"><button type="button" class="btn-floating btn-large waves-effect waves-light"><i class="fa fa-ban"></i></button></a>-->
                        {%endif%}

                        {%if user == R.0.autor%}<!-- Si soy el autor de la review,la puedo modificar o eliminar-->
                        <a href="/modificarReview/{{R.0.id}}/"method="GET" type="button" class="btn-floating btn-large waves-effect waves-light"><i class="fa fa-edit"></i></a>

                        <a href="/eliminarContenido/{{R.0.id}}" type="button" class="btn-floating btn-large waves-effect waves-light"><i class="fa fa-trash"></i></a>
                        {%endif%}   
                    </div>

                  </p>                      
                </li>   
            {%endfor%}
            </ul>
            
        {%else%} <!--si no hay reviews-->
            <h5>0 Reviews </h5>      
        {%endif %}
    </div>
</div> 

<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>No permitido</h4>
      <p>No se admite más de una review por usuario para cada sitio</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Aceptar</a>
    </div>
  </div>

<!-- Modal de Denuncias-->
<div id="myModalDenuncia" class="modal">
    <div class="modal-content">
      <h4>Denunciar</h4>
      <form role="form" action="/denunciar/" method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        {{fDenuncia.as_p}}
        <input type="hidden" name="id_denuncia" id='id_denuncia' value="" />
        <input type="hidden" name="tipo" id="tipo-contenido" value="" />                       
       
    </div>
    <div class="modal-footer">
      <button class=" modal-action modal-close waves-effect waves-green btn-flat" type="submit">Denunciar</button>
      </form>
    </div>
</div>
{%endblock%}

{% block extra_body%}
<link href="{% static "css/bootstrap-rating.css" %}" rel="stylesheet">
<script type="text/javascript" src="{% static "js/bootstrap-rating.min.js" %}"></script>

<script type='text/javascript'>

    $(document).ready(function(){
        $('.parallax').parallax();           
        $('select').material_select();
        $('.rating').rating();
        $('.tooltipped').tooltip({delay: 50});  
        $('.modal-trigger').leanModal();
    });    


    function Refresh(){
       $.ajax({
        url: '/Refresh/',
        data:{"id":id},
        success: function(data) { 
            $("#Contenido").html(data);
        },
        failure: function(data) { 
            alert('Got an error dude');
        }
    });
   }


   $(document).on("click", "#btnComent", function () {
      var myID = $(this).data('id');
      $('#review_id').attr("value",myID);
      console.log("mi id; " + myID);
  });


   $(document).on("click", "#btnDenunciaReview", function () {
      var myID = $(this).data('id');
      $('#id_denuncia').attr("value",myID);
      $('#tipo-contenido').val("Review");
      console.log("mi id; " + myID);
  });

   $("#f-comentario").submit(function(){
    {%for R in lista%}
      {%if user.id == R.0.autor.id%}
        $('#modal1').openModal();
        return false;
      {%endif%}
    {%endfor%}
   });


//var csrftoken = $.cookie('csrftoken');

</script>
{%endblock%}

Contenido/templates/busquedaAvanzada.html
<div class="input-field col s6">
	<input id="buscador" type="text" length="100">
	<label for="buscador">Buscar</label>
</div>
<input type="text" class ="form-control searchInput" id="Busqueda" placeholder="Buscar" data-toggle="">	    	
<ul role="menu" class="dropdown-menu" id = "bajo">
</ul> 

Contenido/templates/establecimiento_text.html
{{object.nombre}}
{{object.ciudad}}

Contenido/templates/followers.html
<ul class="collection">
    {%for follow in followers%}
    <li class="collection-item avatar" id="{{follow.0}}">
     	<img src="{{follow.1}}" alt="" class="circle">
      <span class="title">{{follow.2}}</span>
       
      <a href="#!" class="btn-floating btn-large waves-effect waves-light cyan right" data="{{follow.0}}" id="send{{follow.0}}"onclick="personalMessage(this.getAttribute('data'))"><i class="fa fa-envelope-o"></i></a>
    </li>
    {%endfor%}
</ul>
<!--<a href="#!" class="secondary-content" data="{{follow.0}}" onclick="personalMessage(this.getAttribute('data'))"><i class="fa fa-envelope-o"></i></a>-->